AppPKP/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace AppPKP.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

AppPKP/Pages/Index.cshtml.cs
using AppPKP.Pages.PKP;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;
using System.Collections.Generic;
using static AppPKP.Pages.IndexModel;
using System;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.ViewFeatures;


namespace AppPKP.Pages
{
    public class IndexModel : PageModel
    {


        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnPostLogout()
        {
            HttpContext.Session.Clear();
            return RedirectToPage();
        }


        public List<PolaczeniaInfo> PolaczeniaList = new List<PolaczeniaInfo>();

        public string Godzina { get; set; }
        public string Odjazd { get; set; }
        public string Przyjazd { get; set; }

        public string polaczenieID { get; set;}

        public string nazwaUser { get; set; }

        public void OnPostSearch()
        {

            Godzina = Request.Form["Godzina"];
            Odjazd = Request.Form["Odjazd"];
            Przyjazd = Request.Form["Przyjazd"];
          

            
            try
            {
                string bazaconnectString = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=master;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";

                using (SqlConnection conn = new SqlConnection(bazaconnectString))
                {
                    conn.Open();
                    String polecenie = "SELECT * FROM polaczenia";
                    using (SqlCommand comm = new SqlCommand(polecenie, conn))
                    {
                        using (SqlDataReader reader = comm.ExecuteReader())
                        {
                            while (reader.Read())
                            {

                                PolaczeniaInfo polaczeniaInfo = new PolaczeniaInfo();
                                polaczeniaInfo.id = reader.GetInt32(0); // "" + ....
                                polaczeniaInfo.godzina = reader.GetTimeSpan(1).ToString();
                                polaczeniaInfo.wyjazd = reader.GetString(2);
                                polaczeniaInfo.przyjazd = reader.GetString(3);
                                polaczeniaInfo.droga = reader.GetString(4);

                               

                                TimeSpan ts1, ts2;
                                TimeSpan.TryParse(polaczeniaInfo.godzina, out ts1);
                                TimeSpan.TryParse(Godzina, out ts2);


                                int godzinaInt = (int)ts1.TotalSeconds;
                                int godzinaPageInt = (int)ts2.TotalSeconds;


                                

                                if (godzinaInt >= godzinaPageInt && polaczeniaInfo.wyjazd == Odjazd && polaczeniaInfo.przyjazd == Przyjazd)
                                {
                                    
                                    PolaczeniaList.Add(polaczeniaInfo);
                                    //completeMessage = "Znaleziono!";
                                    
                                }

                                PolaczeniaList = PolaczeniaList.OrderBy(td => TimeSpan.Parse(td.godzina)).ToList();


                              

                            }
                        }
                    }
                }

            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception: " + ex.ToString());
            }



        }
        public void OnPostOrder()
        {

            polaczenieID = Request.Form["polaczenieID"];
            nazwaUser = Request.Form["nazwaUser"];

                if (int.TryParse(polaczenieID, out int polaczenieIDValue))
                {

                    try
                    {

                        string bazaconnectString = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=master;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";
                        using (SqlConnection conn = new SqlConnection(bazaconnectString))
                        {
                            conn.Open();
                            string polecenieinsert = "INSERT INTO bilety (nazwa_USER, polaczenieID) VALUES (@nazwaUser, @polaczenieID)";
                            using (SqlCommand comm = new SqlCommand(polecenieinsert, conn))
                            {
                                comm.Parameters.AddWithValue("@nazwaUser", nazwaUser);
                                comm.Parameters.AddWithValue("@polaczenieID", polaczenieIDValue);

                                comm.ExecuteNonQuery();
                                
                            }
                        }
                    }
                    catch (Exception ex)
                    {

                        Console.WriteLine("Exception: " + ex.ToString());
                    }
                }
            

        }

        public void OnGet()
        {
            //try
            //{
            //    string bazaconnectString = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=master;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";

            //    using (SqlConnection conn = new SqlConnection(bazaconnectString))
            //    {
            //        conn.Open();
            //        String polecenie = "INSERT INTO zamowienie (godzina, wyjazd, przyjazd, droga) VALUES (@godzina, @wyjazd, @przyjazd, @droga)";
            //        using (SqlCommand comm = new SqlCommand(polecenie, conn))
            //        {
            //            comm.Parameters.AddWithValue("@godzina", Imie);
            //            comm.Parameters.AddWithValue("@wyjazd", Nazwisko);
            //            comm.Parameters.AddWithValue("@przyjazd", Email);
            //            comm.Parameters.AddWithValue("@droga", hashedPassword);
                
            //        }
            //    }

            //}
            //catch (Exception ex)
            //{
            //    Console.WriteLine("Exception: " + ex.ToString());
            //}
        }

       



        public class PolaczeniaInfo
        {
            public int id;
            public string godzina;
            public string wyjazd;
            public string przyjazd;
            public string droga;
        }
    }
}

AppPKP/Pages/PKP/Dodaj.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using static AppPKP.Pages.IndexModel;
using System.Data.SqlClient;
using System.Reflection.PortableExecutable;
using System.Security.Cryptography;
using System.Text;
using AppPKP.Pages.PKP;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Mvc.ModelBinding.Binders;
using Microsoft.EntityFrameworkCore.Internal;
using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore.Metadata.Conventions.Infrastructure;
using Microsoft.Identity.Client;

namespace AppPKP.Pages.PKP
{
    public class DodajModel : PageModel
    {

        public string nazwaUser { get; set; }
        public string Godzina { get; set; }
        public string Odjazd { get; set; }
        public string Przyjazd { get; set; }

        public string Trasa { get; set; }

        public bool isSu { get; set; }

        public string mess = "";


        protected void PageLoad(object sender, EventArgs e)
        {

              
            
        }


        public void OnGet()
        {

        }

        public void OnPost()
        {
            isSu = ZmienneSesja.sUser;

            Godzina = Request.Form["Godzina"];
            Odjazd = Request.Form["Odjazd"];
            Przyjazd = Request.Form["Przyjazd"];
            Trasa = Request.Form["Trasa"];
            if (isSu == true)
            {
                if (Godzina.Length != 0 && Odjazd.Length != 0 && Przyjazd.Length != 0 && Trasa.Length != 0)
                {


                    try
                    {
                        string bazaconnectString = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=master;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";

                        using (SqlConnection conn = new SqlConnection(bazaconnectString))
                        {
                            conn.Open();
                            String polecenie = "INSERT INTO polaczenia (godzina, wyjazd, przyjazd, droga) VALUES (@Godzina, @Odjazd, @Przyjazd, @Trasa)";
                            using (SqlCommand comm = new SqlCommand(polecenie, conn))
                            {

                                comm.Parameters.AddWithValue("@Godzina", Godzina);
                                comm.Parameters.AddWithValue("@Odjazd", Odjazd);
                                comm.Parameters.AddWithValue("@Przyjazd", Przyjazd);
                                comm.Parameters.AddWithValue("@Trasa", Trasa);


                                comm.ExecuteNonQuery();
                                mess = "Pomyslnie dodano polaczenie!";
                            }
                        }

                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine("Exception: " + ex.ToString());
                    }
                }
                else
                {
                    mess = "Wprowadz wszystkie pola!";
                    return;
                }
            }
            else
            {

                mess = "Brak uprawnien";
            }

        }
    }
}

AppPKP/Pages/PKP/Rozklad.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Data.SqlClient;
using System.Security.Cryptography;
using System.Text;
using AppPKP.Pages.PKP;
using Microsoft.AspNetCore.Authorization.Infrastructure;
using Microsoft.AspNetCore.Mvc.ModelBinding.Binders;
using Microsoft.EntityFrameworkCore.Internal;
using System.ComponentModel.DataAnnotations;
using static AppPKP.Pages.IndexModel;
using Microsoft.EntityFrameworkCore.Metadata.Conventions.Infrastructure;

namespace AppPKP.Pages.PKP
{
    public class RozkladModel : PageModel
    {
       
        public List<RozkladInfo> RozkladList = new List<RozkladInfo>();
        public void OnGet()
        {

            try
            {
                string bazaconnectString = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=master;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";

                using (SqlConnection conn = new SqlConnection(bazaconnectString))
                {
                    conn.Open();
                    String polecenie = "SELECT * FROM polaczenia";
                    using (SqlCommand comm = new SqlCommand(polecenie, conn))
                    {
                        using(SqlDataReader reader = comm.ExecuteReader())
                        {
                            while(reader.Read())
                            {
                                RozkladInfo rozkladInfo = new RozkladInfo();
                                rozkladInfo.id = reader.GetInt32(0); // "" + ....
                                rozkladInfo.godzina = reader.GetTimeSpan(1).ToString();
                                rozkladInfo.wyjazd = reader.GetString(2);
                                rozkladInfo.przyjazd = reader.GetString(3);
                                rozkladInfo.droga = reader.GetString(4);

                                RozkladList.Add(rozkladInfo);

                                RozkladList = RozkladList.OrderBy(td => TimeSpan.Parse(td.godzina)).ToList();

                            }
                        }
                    }
                }

            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception: " + ex.ToString());
            }
        }

        //public int tempSite = 1;


        //public void Poprzedni()
        //{

        //    if (tempSite > 1)
        //    {
        //        tempSite--;
        //    }
        //}
        //public void Kolejny()
        //{
        //   if(tempSite < RozkladList.Count)
        //    {
        //        tempSite++;
        //    }

        //}


    }
    public class RozkladInfo
    {
        public int id; // string
        public string godzina;
        public string wyjazd;
        public string przyjazd;
        public string droga;
    }
    
   
  
}

AppPKP/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AppPKP.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

AppPKP/Pages/Dodaj.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "PKP - Dodaj polaczenie";
}

<div id="ramka">
    <h1 class="display-4">Dodaj polaczenie!</h1><br />

   
    <div>
        
    </div>
    <br />

    <button id="dodaj">Dodaj polaczenie</button>
</div>

AppPKP/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "PKP - Wyszukaj polaczenie";
}


@{

    var nazwaUser = Request.HttpContext.Session.GetString(ZmienneSesja.sesjaUser);
    int id = 0;
    
}


  
<div class="text-center">
    


    <div id="ramka">
        <h1 class="display-4">Wyszukaj polaczenie!</h1><br />

        <button id="rozklad"><a class="nav-link text-dark" asp-area="" asp-page="/PKP/Rozklad">Rozklad jazdy</a></button><br /><br />

        <div>

            <form method="post" asp-page-handler="Search">
                <label for="Godzina">Godzina:</label>
                <input name="Godzina" type="time" size="50" id="godz" /><br /><br />

                <label for="Odjazd">Odjazd:</label>
                <input name="Odjazd" type="text" size="50" id="odj" /> <br /><br />
                
                <label for="Przyjazd">Przyjazd:</label>
                <input name="Przyjazd" type="text" size="50" id="przyj" /> <br /><br />

                <button type="submit" id="submitBtn">Wyszukaj</button>
            </form>
            <br /><br />
                        
                        @foreach (var item in Model.PolaczeniaList)
                        {

                            id += 1;

                           
                                
                                
                                @if (!string.IsNullOrWhiteSpace(nazwaUser))
                                {
                                    //przejscie do zakladki user -> bilety
                                    <form method="post" asp-page-handler="Order">
                                        <div>
                                            @* <p>Zamówienie nr @item.id</p> *@
                                            <table>
                                                <tb>
                                                    <tr>
                                                        <td>@item.godzina  -  </td>
                                                        <td>@item.wyjazd  -  </td>
                                                        <td>@item.przyjazd  -  </td>
                                                        <td>@item.droga</td>
                                                        <input type="hidden" name="nazwaUser" value="@nazwaUser">
                                                        <input type="hidden" name="polaczenieID" value="@item.id">
                                                        <td><button type="submit">Zamów</button></td>
                                                    </tr>
                                                </tb>
                                            </table>
    
                                           
                                        </div>
                                    </form>
                                      @* <td><button><a id="abilet" href="/PKP/User" onclick="OnPost()">Kup bilet</a></button></td> *@

                                      @*<td><asp:Button ID="myButton" runat="server" Text="Kliknij mnie" OnClick="button_kup" />tests</td>*@


                                  
                                    
                                }
                                else
                                {
                                    <div>
                                        @* <p>Zamówienie nr @item.id</p> *@
                                        <table>
                                            <tb>
                                                <tr>
                                                    <td>@item.godzina  -  </td>
                                                    <td>@item.wyjazd  -  </td>
                                                    <td>@item.przyjazd  -  </td>
                                                    <td>@item.droga</td>
                                                    <td> <button id="bilet"><a id="abilet" href="/PKP/Login">Kup bilet</a></button></td>
                                                </tr>
                                            </tb>
                                        </table>

                                        @* <button type="submit" name="orderId" href="/PKP/Login">Zamów</button> *@
                                    </div>
                                    @* <td><button id="bilet"><a id="abilet" href="/PKP/Login">Kup bilet</a></button></td> *@
                                }
                                
                         
                        }

        </div>
        <br />

        
        
    </div>
   
</div>

AppPKP/Pages/Rozklad.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "PKP - Rozklad jazdy";
}

<div id="ramka">
    <h1 class="display-4">Rozklad jazdy!</h1><br />

   
    <div>
        
    </div>
    <br />

    <button id="poprzednie">Poprzednie polaczenie</button>
    <button id="nastepne">Nastepne polaczenie</button>
</div>

AppPKP/Pages/_ViewStart1.cshtml
@{
    Layout = "_Layout";
}